hard_tabs = true
max_width = 80
reorder_imports = true
newline_style = "Unix"
use_field_init_shorthand = true
comment_width = 80
format_code_in_doc_comments = true
imports_granularity = "Crate"
imports_layout = "Vertical"
wrap_comments = true
use_small_heuristics = "Max"
fn_args_layout = "Compressed"
